version: '3.1'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./app:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0 --reload"
    depends_on:
      - mysql-test
  
  mysql:
    image: mysql:5.7
    volumes:
      - $HOME/docker-databases/mysql-db/api-gateway:/var/lib/mysql
    env_file:
      - ./.env
    ports:
      - 3306:3306
  
  mysql-test:
    image: mysql:5.7
    volumes:
      - $HOME/docker-databases/mysql-db/api-gateway-test:/var/lib/mysql
    env_file:
      - ./.env
    ports:
      - 3307:3306
    depends_on:
      - mysql